### ISSUE TITLE
Failure to parse homogeneous arrays with strict_arrays enabled

### ISSUE THREAD

**Issue by oschwald** [sysread/TOML-Tiny#10]
When `strict_arrays` are enabled, parsing of some homogeneous arrays fails with unexpected type errors. For instance, parsing:

```toml
[test]
array = ["u", "u2"]
```

Fails with:

```
toml parse error at line EOF: expected value of type string, but found integer
```

Given that TOML 1.0 now [supports heterogeneous arrays](https://github.com/toml-lang/toml/pull/676), it might make sense to remove `strict_arrays` altogether. However, this issue may point to a more general problem with the type detection.

**Comment by sysread** [comment]
Sorry it took so long to respond. I will update to allow heterogeneous arrays. It may take a bit longer to update for other changes in 1.0 because I haven't been paying much attention to it recently :P

**Comment by sysread** [comment]
Fixed in https://github.com/sysread/TOML-Tiny/releases/tag/v0.11

I may well remove that in a future version, but in the meantime, the bug is fixed.

**Comment by oschwald** [comment]
Thank you!
