### ISSUE TITLE
0.14 fails to quote strings with "inf" in them

### ISSUE THREAD

**Issue by oschwald** [sysread/TOML-Tiny#16]
As of the 0.14 release, `TOML::Tiny` fails to quote string values with "inf" or "nan"  in them. For instance:

```perl
use TOML::Tiny;

print to_toml({ 'a' => 'to be informed'});
```

outputs:

```
a=to be informed
```

**Comment by sysread** [comment]
Just pushed v0.15 to cpan with the fix.

**Comment by oschwald** [comment]
Thanks!
